apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      shareProcessNamespace: true
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config-v01
        - name: proxy-config
          configMap:
            name: proxy-config
      containers:
        - name: nginx
          image: nginx:1.25.3-alpine
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
            - name: proxy-config
              mountPath: /etc/nginx/conf.d
              readOnly: true
        - name: nginx-reloader
          image: wangxiaowu950330/nginx-reloader:latest
          env:
            - name: WATCH_NGINX_CONF_PATH
              value: /etc/nginx/conf.d
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/config
              readOnly: true
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
    - name: http
      port: 80
      nodePort: 32080
    - name: https
      port: 443
      nodePort: 32443
