apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      shareProcessNamespace: true
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
        - name: nginx-proxy-config
          configMap:
            name: nginx-proxy-config
        - name: nginx-log
          emptyDir: {}
      containers:
        - name: nginx
          image: nginx:1.25.3
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
            - name: nginx-proxy-config
              mountPath: /etc/nginx/conf.d
              readOnly: true
            - name: nginx-log
              mountPath: /etc/nginx/logs
        - name: nginx-reloader
          image: wangxiaowu950330/nginx-reloader:latest
          env:
            # fsnotify不支持子目录递归，所以此处做了调整，value值可用英文逗号拼接多个路径
            # 但需要记得其他的文件夹也要挂载到nginx-reloader容器下
            - name: WATCH_NGINX_CONF_PATH
              value: /etc/nginx/conf.d
          volumeMounts:
            - name: nginx-proxy-config
              mountPath: /etc/nginx/conf.d
              readOnly: true
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
    - name: http
      port: 80
      nodePort: 32080
    - name: https
      port: 443
      nodePort: 32443
